import re
import json

filepath = '/Users/sidsmac/Documents/ADMAZIC/seo-in-surat.html'
outpath = '/Users/sidsmac/Documents/ADMAZIC/meta-ads-in-surat.html'

with open(filepath, 'r', encoding='utf-8') as f:
    content = f.read()

header_match = re.search(r'(.*?</header>)', content, re.DOTALL)
header = header_match.group(1)
footer_match = re.search(r'(<footer class="footer".*)', content, re.DOTALL)
footer = footer_match.group(1)

# Modify the title and meta in header
header = re.sub(r'<title>.*?</title>', '<title>Meta Ads Services in Surat | Facebook & Instagram Ads Agency | ADMAZIC</title>', header)
header = re.sub(r'<meta name="description" content=".*?">', '<meta name="description" content="Looking for the best Meta Ads services in Surat? ADMAZIC helps businesses scale with data-driven Facebook and Instagram advertising campaigns.">', header)

meta_faqs = [
    {"q": "How much should I spend on Meta Ads in Surat?", "a": "For local businesses in Surat, we recommend starting with a minimum budget of ₹20,000 to ₹30,000 per month. For D2C ecommerce brands and luxury real estate, budgets typically range from ₹1,00,000 to ₹5,000,000+ per month to aggressively scale acquisitions."},
    {"q": "Are Meta Ads better than Google Ads for my business?", "a": "They serve different purposes. Google Ads captures existing search intent (people already looking for a product). Meta Ads (Facebook & Instagram) generate demand through visual storytelling, making them incredible for brand awareness, impulse purchases, and scaling D2C brands."},
    {"q": "Can Meta Ads generate leads for my B2B or service business?", "a": "Absolutely. Using targeted Lead Generation campaigns and WhatsApp funnels, we generate high-quality inquiries for real estate developers, interior designers, educational institutes, and B2B service providers in Surat."},
    {"q": "Is Meta Ads suitable for local businesses like restaurants or clinics?", "a": "Yes! Meta's hyper-local geo-targeting allows you to show ads to people within a 2km to 5km radius of your physical location in areas like Vesu or Adajan, making it perfect for driving footfall and local brand dominance."},
    {"q": "What campaign type should I use for my ecommerce store?", "a": "For ecommerce, we heavily utilize Conversion campaigns optimized for Purchases, alongside dynamic Catalogue Sales ads that automatically show users the exact products they previously viewed on your website."},
    {"q": "What is the Meta Pixel and why do I need it?", "a": "The Meta Pixel is a piece of code installed on your website that tracks user behaviour. It is absolutely essential for measuring conversions, optimizing campaigns, and building retargeting audiences (e.g., showing ads to people who abandoned their cart)."},
    {"q": "Can Meta Ads generate WhatsApp leads?", "a": "Yes. 'Click to WhatsApp' campaigns are highly effective in Surat, as consumers prefer direct conversational commerce. We use these extensively for real estate, fashion boutiques, and high-ticket service inquiries."},
    {"q": "Do I need a landing page for Meta Ads?", "a": "While you can run on-platform lead forms or WhatsApp ads without a website, having a dedicated, fast-loading landing page significantly increases trust, allows for complex conversion tracking, and improves the quality of leads generated."},
    {"q": "What kind of creatives work best on Facebook and Instagram?", "a": "Video is king. Short-form Reels, founder stories, user-generated content (UGC), and authentic product demonstrations outperform highly polished static graphics in almost every industry."},
    {"q": "Which businesses perform best on Meta Ads in Surat?", "a": "Fashion and apparel brands (D2C), real estate developers, jewelry businesses, educational coaching institutes, healthcare clinics, and interior designers see exceptional ROI due to the visual nature of their products and services."},
    {"q": "How do you handle retargeting?", "a": "We build multi-step retargeting funnels. For example, if someone watches 50% of your video ad but doesn't buy, we retarget them with a carousel ad highlighting customer testimonials, followed by an urgency-driven offer ad."},
    {"q": "Why is my current Meta Ads campaign not working?", "a": "Common reasons include ad fatigue (using the same creative for too long), poor audience targeting, broken pixel tracking, or an optimized funnel where the landing page fails to convert the clicks generated by the ads."},
    {"q": "Do you setup the Conversion API (CAPI)?", "a": "Yes. With iOS14+ privacy changes and browser cookie restrictions, setting up the Meta Conversion API (server-side tracking) is mandatory to ensure accurate data attribution and campaign optimization."},
    {"q": "How long does it take to see results?", "a": "Meta Ads can drive traffic and leads on day one. However, the algorithm typically requires 7 to 14 days of 'learning phase' data to stabilize CPA (Cost Per Acquisition) and optimize delivery to the highest-converting users."},
    {"q": "Can you audit my existing Meta Ads account?", "a": "Yes, we provide comprehensive Meta Ads audits. We review your campaign structure, pixel setup, creative assets, audience overlap, and bidding strategies to identify wasted spend and immediate growth opportunities."}
]

schema_data = {
  "@context": "https://schema.org",
  "@type": "FAQPage",
  "mainEntity": [{"@type": "Question", "name": faq["q"], "acceptedAnswer": {"@type": "Answer", "text": faq["a"]}} for faq in meta_faqs]
}
schema_json = json.dumps(schema_data, indent=2)

header = re.sub(r'<script type="application/ld\+json">.*?</script>', lambda _: f'<script type="application/ld+json">\n{schema_json}\n</script>', header, flags=re.DOTALL)

new_body = f"""
  <!-- Section 1: Hero Section -->
  <section class="hero bg-grid" style="position: relative; padding-top: 180px; padding-bottom: 120px;">
    <div class="container" style="position: relative; z-index: 2; text-align: center; display: flex; flex-direction: column; align-items: center;">
      <div class="reveal text-reveal-up" style="margin-bottom: 20px;">
        <span class="section-tag" style="background: rgba(31,83,151,0.1); color: var(--accent-blue); border: 1px solid rgba(31,83,151,0.2);">Premium Meta Ads Services in Surat</span>
      </div>
      <h1 class="hero-title reveal text-reveal-up delay-1" style="font-size: clamp(2.5rem, 5vw, 4.5rem); font-weight: 800; max-width: 950px; margin: 0 auto 24px auto; color: var(--text-primary); line-height: 1.1;">
        Scale Your Brand & Revenue With <br><span class="text-highlight">Meta Ads in Surat</span>
      </h1>
      <p class="hero-description reveal text-reveal-up delay-2" style="font-size: 1.2rem; max-width: 900px; margin: 0 auto 40px auto; color: var(--text-secondary); line-height: 1.8;">
        Stop relying on unpredictable organic reach. We engineer highly profitable Facebook and Instagram advertising campaigns that generate qualified leads, explode D2C ecommerce sales, and build massive brand authority across South Gujarat. Turn scrolling attention into tangible business growth with our data-driven creative strategies and advanced funnel architecture.
      </p>
      <div class="hero-buttons reveal text-reveal-up delay-3" style="display: flex; gap: 20px; justify-content: center; flex-wrap: wrap;">
        <a href="free-audit" class="btn btn-primary glow-btn" style="padding: 18px 40px; font-size: 1.1rem; background-color: #DC2626; color: #fff;">Book a Free Strategy Session <i class="fas fa-arrow-right btn-icon"></i></a>
        <a href="tel:+917861910348" class="btn btn-secondary" style="padding: 18px 40px; font-size: 1.1rem;"><i class="fas fa-phone-alt"></i> Call +91 78619 10348</a>
      </div>
    </div>
  </section>

  <!-- Section 2: Why Meta Ads Work For Businesses in Surat -->
  <section class="section" style="background-color: var(--bg-secondary); border-top: 1px solid var(--glass-border); padding: 100px 0;">
    <div style="max-width: 1400px; margin: 0 auto; padding: 0 20px;">
      <div class="section-header reveal" style="text-align: center; margin-bottom: 50px;">
        <h2 class="section-title" style="color: var(--text-primary);">Why Meta Ads Work For Businesses in Surat</h2>
        <p class="section-subtitle" style="color: var(--text-secondary);">Demand generation vs. Demand capture. The power of visual storytelling.</p>
      </div>
      
      <div class="comparison-grid reveal surat-grid-3">
        <div class="glass-card" style="background: var(--bg-primary); border: 1px solid var(--glass-border); padding: 40px; border-radius: 12px;">
          <div class="card-icon" style="color: var(--accent-blue); font-size: 2.5rem; margin-bottom: 20px;"><i class="fab fa-instagram"></i></div>
          <h3 class="card-title" style="color: var(--text-primary); font-size: 1.5rem; margin-bottom: 15px;">Visual Buying Behaviour</h3>
          <p style="color: var(--text-secondary); line-height: 1.8; font-size: 1.05rem;">
            Surat is a city driven by aesthetics—from luxury real estate projects in Vesu to designer ethnic wear on Ring Road. Meta Ads (specifically Instagram) excel in visually-driven markets. You aren't just selling a product; you are selling a lifestyle. High-quality visual creatives allow you to generate demand before a customer even realizes they need your product.
          </p>
        </div>
        <div class="glass-card" style="background: var(--bg-primary); border: 1px solid var(--glass-border); padding: 40px; border-radius: 12px;">
          <div class="card-icon" style="color: var(--accent-blue); font-size: 2.5rem; margin-bottom: 20px;"><i class="fas fa-bullhorn"></i></div>
          <h3 class="card-title" style="color: var(--text-primary); font-size: 1.5rem; margin-bottom: 15px;">Proactive Demand Generation</h3>
          <p style="color: var(--text-secondary); line-height: 1.8; font-size: 1.05rem;">
            While Google Ads relies on someone actively searching for a keyword, Meta Ads push your brand into the feeds of your exact target demographic. This is how you build massive market awareness. The customer journey on Meta is proactive: <strong>Discovery &rarr; Engagement &rarr; Consideration &rarr; Lead Generation &rarr; Sales</strong>.
          </p>
        </div>
        <div class="glass-card" style="background: var(--bg-primary); border: 1px solid var(--glass-border); padding: 40px; border-radius: 12px;">
          <div class="card-icon" style="color: var(--accent-blue); font-size: 2.5rem; margin-bottom: 20px;"><i class="fas fa-mobile-alt"></i></div>
          <h3 class="card-title" style="color: var(--text-primary); font-size: 1.5rem; margin-bottom: 15px;">Mobile-First Audiences</h3>
          <p style="color: var(--text-secondary); line-height: 1.8; font-size: 1.05rem;">
            Over 90% of Surat's digital consumption happens on mobile devices, primarily within the Facebook and Instagram ecosystems. By leveraging vertical video (Reels and Stories) and frictionless mobile conversion paths like WhatsApp lead generation, businesses can seamlessly integrate into the daily scrolling habits of their target market.
          </p>
        </div>
      </div>
      <div class="reveal" style="margin-top: 50px; text-align: center; display: flex; justify-content: center; width: 100%;">
        <a href="free-audit" class="btn btn-secondary" style="padding: 15px 35px; display: inline-block;"><i class="fas fa-rocket"></i> Launch Your Meta Campaign</a>
      </div>
    </div>
  </section>

  <!-- Section 3: Digital Buying Behaviour in Surat -->
  <section class="section" style="padding: 100px 0;">
    <div class="container">
      <div class="section-header reveal" style="text-align: center; margin-bottom: 40px;">
        <h2 class="section-title" style="color: var(--text-primary);">Digital Buying Behaviour in Surat</h2>
        <p class="section-subtitle" style="color: var(--text-secondary); max-width: 800px; text-align: center; margin: 0 auto;">How your customers interact with brands on social media.</p>
      </div>
      <div class="content-text reveal" style="color: var(--text-secondary); font-size: 1.15rem; line-height: 1.9; text-align: center; max-width: 1000px; margin: 0 auto;">
        <p style="margin-bottom: 25px;">
          The digital adoption rate among businesses and consumers in Surat has skyrocketed. We are witnessing a clear divergence in social media consumption patterns. Instagram has become the primary discovery engine for younger demographics, high-net-worth individuals, and premium lifestyle brands. Whether it's discovering a new cafe in Piplod, exploring interior design trends, or shopping for D2C fashion, Instagram Reels and Stories drive the initial engagement.
        </p>
        <p style="margin-bottom: 25px;">
          Conversely, Facebook remains incredibly powerful for broader audience reach, community building, and targeting older demographics with higher purchasing power. It is highly effective for real estate lead generation, B2B manufacturing inquiries, and educational institute enrollments. Surat's consumers are highly conversational; they prefer clicking an ad that takes them directly to a WhatsApp chat with a business owner rather than filling out a complex form.
        </p>
        <p>
          To succeed in this landscape, businesses must stop treating Meta as a place for organic 'post boosting' and start treating it as a highly sophisticated, data-driven customer acquisition platform that requires strategic funnel mapping and relentless creative testing.
        </p>
      </div>
    </div>
  </section>

  <!-- Section 4: Industries That Perform Well -->
  <section class="section" style="background-color: var(--bg-secondary); border-top: 1px solid var(--glass-border); padding: 100px 0;">
    <div class="container">
      <div class="section-header reveal" style="text-align: center; margin-bottom: 50px;">
        <h2 class="section-title" style="color: var(--text-primary);">Industries Thriving on Meta Ads in Surat</h2>
        <p class="section-subtitle" style="color: var(--text-secondary);">Visual platforms demand visual industries.</p>
      </div>
      <div class="surat-grid-3 reveal">
        <div style="background: var(--bg-primary); padding: 35px; border-radius: 12px; border: 1px solid var(--glass-border); text-align: center;">
          <div style="font-size: 2.2rem; color: var(--accent-blue); margin-bottom: 15px;"><i class="fas fa-building"></i></div>
          <h3 style="color: var(--text-primary); margin-bottom: 15px;">Real Estate Developers</h3>
          <p style="color: var(--text-secondary); font-size: 1rem; line-height: 1.6;"><strong>Strategy:</strong> Lead Generation using high-quality video walkthroughs of sample flats in Vesu or Adajan, combined with Carousel ads showcasing amenities. <strong>Funnel:</strong> Video View &rarr; Lead Form &rarr; CRM &rarr; Site Visit.</p>
        </div>
        <div style="background: var(--bg-primary); padding: 35px; border-radius: 12px; border: 1px solid var(--glass-border); text-align: center;">
          <div style="font-size: 2.2rem; color: var(--accent-blue); margin-bottom: 15px;"><i class="fas fa-shopping-bag"></i></div>
          <h3 style="color: var(--text-primary); margin-bottom: 15px;">D2C Fashion & Apparel</h3>
          <p style="color: var(--text-secondary); font-size: 1rem; line-height: 1.6;"><strong>Strategy:</strong> Aggressive Conversion campaigns optimizing for direct website purchases. Utilizing dynamic Catalogue Sales and highly engaging Instagram Reels showcasing the apparel in motion.</p>
        </div>
        <div style="background: var(--bg-primary); padding: 35px; border-radius: 12px; border: 1px solid var(--glass-border); text-align: center;">
          <div style="font-size: 2.2rem; color: var(--accent-blue); margin-bottom: 15px;"><i class="fas fa-gem"></i></div>
          <h3 style="color: var(--text-primary); margin-bottom: 15px;">Jewellery Brands</h3>
          <p style="color: var(--text-secondary); font-size: 1rem; line-height: 1.6;"><strong>Strategy:</strong> Building brand prestige through hyper-targeted Awareness campaigns to high-net-worth individuals, followed by Retargeting campaigns highlighting trust, certification, and exclusive collections.</p>
        </div>
        <div style="background: var(--bg-primary); padding: 35px; border-radius: 12px; border: 1px solid var(--glass-border); text-align: center;">
          <div style="font-size: 2.2rem; color: var(--accent-blue); margin-bottom: 15px;"><i class="fas fa-utensils"></i></div>
          <h3 style="color: var(--text-primary); margin-bottom: 15px;">Restaurants & Cafes</h3>
          <p style="color: var(--text-secondary); font-size: 1rem; line-height: 1.6;"><strong>Strategy:</strong> Hyper-local radius targeting (2-5km) using mouth-watering video creatives and limited-time offer ads to drive immediate footfall and weekend reservations.</p>
        </div>
        <div style="background: var(--bg-primary); padding: 35px; border-radius: 12px; border: 1px solid var(--glass-border); text-align: center;">
          <div style="font-size: 2.2rem; color: var(--accent-blue); margin-bottom: 15px;"><i class="fas fa-couch"></i></div>
          <h3 style="color: var(--text-primary); margin-bottom: 15px;">Interior Designers</h3>
          <p style="color: var(--text-secondary); font-size: 1rem; line-height: 1.6;"><strong>Strategy:</strong> Before-and-after Carousel ads and client testimonial videos targeting new homeowners, driving them to a consultation booking landing page or direct WhatsApp inquiry.</p>
        </div>
        <div style="background: var(--bg-primary); padding: 35px; border-radius: 12px; border: 1px solid var(--glass-border); text-align: center;">
          <div style="font-size: 2.2rem; color: var(--accent-blue); margin-bottom: 15px;"><i class="fas fa-graduation-cap"></i></div>
          <h3 style="color: var(--text-primary); margin-bottom: 15px;">Educational Institutes</h3>
          <p style="color: var(--text-secondary); font-size: 1rem; line-height: 1.6;"><strong>Strategy:</strong> Multi-layered funnels targeting both students (Instagram) and parents (Facebook) highlighting campus life, placement records, and driving admission inquiries.</p>
        </div>
      </div>
    </div>
  </section>

  <!-- Section 5: Meta Ads Services We Offer -->
  <section class="section" style="padding: 100px 0;">
    <div class="container">
      <div class="section-header reveal" style="text-align: center; margin-bottom: 50px;">
        <h2 class="section-title" style="color: var(--text-primary);">Our Comprehensive Meta Ads Services</h2>
        <p class="section-subtitle" style="color: var(--text-secondary);">End-to-end campaign architecture and execution.</p>
      </div>
      <div class="content-text reveal" style="color: var(--text-secondary); font-size: 1.1rem; line-height: 1.8;">
        <ul style="list-style: none; padding: 0; display: grid; grid-template-columns: repeat(auto-fit, minmax(350px, 1fr)); gap: 20px;">
          <li style="background: rgba(255,255,255,0.02); padding: 25px; border-left: 4px solid var(--accent-blue); border-radius: 8px;"><strong>Facebook & Instagram Ads:</strong> Complete management across both platforms, Feed, Stories, and Reels.</li>
          <li style="background: rgba(255,255,255,0.02); padding: 25px; border-left: 4px solid var(--accent-blue); border-radius: 8px;"><strong>Lead Generation Campaigns:</strong> Native lead forms that capture data seamlessly without users leaving the app.</li>
          <li style="background: rgba(255,255,255,0.02); padding: 25px; border-left: 4px solid var(--accent-blue); border-radius: 8px;"><strong>Website Conversion Campaigns:</strong> Driving high-intent traffic designed to purchase, book, or sign up on your site.</li>
          <li style="background: rgba(255,255,255,0.02); padding: 25px; border-left: 4px solid var(--accent-blue); border-radius: 8px;"><strong>WhatsApp Campaigns:</strong> "Click to WhatsApp" ads to initiate immediate, conversational sales processes.</li>
          <li style="background: rgba(255,255,255,0.02); padding: 25px; border-left: 4px solid var(--accent-blue); border-radius: 8px;"><strong>Catalogue Sales Campaigns:</strong> Dynamic e-commerce ads syncing directly with your Shopify or WooCommerce store.</li>
          <li style="background: rgba(255,255,255,0.02); padding: 25px; border-left: 4px solid var(--accent-blue); border-radius: 8px;"><strong>Creative Strategy:</strong> Scripting, storyboarding, and directing high-converting video and static creatives.</li>
          <li style="background: rgba(255,255,255,0.02); padding: 25px; border-left: 4px solid var(--accent-blue); border-radius: 8px;"><strong>Meta Pixel & CAPI Setup:</strong> Advanced server-side tracking to ensure no conversion data is lost to iOS updates.</li>
          <li style="background: rgba(255,255,255,0.02); padding: 25px; border-left: 4px solid var(--accent-blue); border-radius: 8px;"><strong>Campaign Audits:</strong> Deep dives into existing ad accounts to restructure and stop wasted ad spend immediately.</li>
        </ul>
      </div>
      <div class="reveal" style="margin-top: 50px; text-align: center; display: flex; justify-content: center; width: 100%;">
        <a href="free-audit" class="btn btn-primary" style="padding: 15px 35px; background: var(--accent-blue); display: inline-block;">Get a Custom Growth Plan <i class="fas fa-arrow-right"></i></a>
      </div>
    </div>
  </section>

  <!-- Section 6: Our Meta Ads Strategy -->
  <section class="section" style="background-color: var(--bg-secondary); border-top: 1px solid var(--glass-border); padding: 100px 0;">
    <div class="container">
      <div class="section-header reveal" style="text-align: center; margin-bottom: 50px;">
        <h2 class="section-title" style="color: var(--text-primary);">Our Proven Meta Ads Strategy</h2>
        <p class="section-subtitle" style="color: var(--text-secondary);">We don't guess. We research, test, and scale based on data.</p>
      </div>
      
      <div class="process-timeline reveal" style="max-width: 900px; margin: 0 auto;">
        <div style="display: flex; margin-bottom: 30px; background: var(--bg-primary); padding: 35px; border-radius: 12px; border: 1px solid var(--glass-border);">
          <div style="font-size: 2.5rem; font-weight: 800; color: var(--accent-blue); margin-right: 30px; opacity: 0.8;">01</div>
          <div>
            <h3 style="color: var(--text-primary); margin-bottom: 10px; font-size: 1.4rem;">Business, Offer & Audience Research</h3>
            <p style="color: var(--text-secondary); line-height: 1.7;">We start by analyzing your unit economics. We study your competitors in Surat and globally to craft an irresistible offer. We then build highly segmented audience personas based on demographics, interests, and purchasing behaviours.</p>
          </div>
        </div>
        <div style="display: flex; margin-bottom: 30px; background: var(--bg-primary); padding: 35px; border-radius: 12px; border: 1px solid var(--glass-border);">
          <div style="font-size: 2.5rem; font-weight: 800; color: var(--accent-blue); margin-right: 30px; opacity: 0.8;">02</div>
          <div>
            <h3 style="color: var(--text-primary); margin-bottom: 10px; font-size: 1.4rem;">Creative Strategy & Planning</h3>
            <p style="color: var(--text-secondary); line-height: 1.7;">Creative is the new targeting on Meta. We design a matrix of ad creatives—including user-generated content (UGC), founder stories, and graphic carousels—each designed to hook attention within the first 3 seconds.</p>
          </div>
        </div>
        <div style="display: flex; margin-bottom: 30px; background: var(--bg-primary); padding: 35px; border-radius: 12px; border: 1px solid var(--glass-border);">
          <div style="font-size: 2.5rem; font-weight: 800; color: var(--accent-blue); margin-right: 30px; opacity: 0.8;">03</div>
          <div>
            <h3 style="color: var(--text-primary); margin-bottom: 10px; font-size: 1.4rem;">Tracking Setup & Funnel Alignment</h3>
            <p style="color: var(--text-secondary); line-height: 1.7;">Before launching, we ensure the Meta Pixel, Conversions API, and custom events are firing flawlessly. We review the landing page or lead form to ensure a frictionless transition from ad click to conversion.</p>
          </div>
        </div>
        <div style="display: flex; margin-bottom: 30px; background: var(--bg-primary); padding: 35px; border-radius: 12px; border: 1px solid var(--glass-border);">
          <div style="font-size: 2.5rem; font-weight: 800; color: var(--accent-blue); margin-right: 30px; opacity: 0.8;">04</div>
          <div>
            <h3 style="color: var(--text-primary); margin-bottom: 10px; font-size: 1.4rem;">Testing & Campaign Launch</h3>
            <p style="color: var(--text-secondary); line-height: 1.7;">We launch structured testing campaigns (Dynamic Creative Optimization) to pit different headlines, videos, and audiences against each other to identify the winning combinations with statistical significance.</p>
          </div>
        </div>
        <div style="display: flex; background: var(--bg-primary); padding: 35px; border-radius: 12px; border: 1px solid var(--glass-border);">
          <div style="font-size: 2.5rem; font-weight: 800; color: var(--accent-blue); margin-right: 30px; opacity: 0.8;">05</div>
          <div>
            <h3 style="color: var(--text-primary); margin-bottom: 10px; font-size: 1.4rem;">Optimization, Scaling & Reporting</h3>
            <p style="color: var(--text-secondary); line-height: 1.7;">Once we identify the winning ads that meet your target Cost Per Acquisition (CPA), we ruthlessly turn off the losers and horizontally/vertically scale the budgets on the winners. All metrics are transparently reported via live dashboards.</p>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- Section 7: Meta Ads Sales Funnel Strategy -->
  <section class="section" style="padding: 100px 0;">
    <div class="container">
      <div class="section-header reveal" style="text-align: center; margin-bottom: 50px;">
        <h2 class="section-title" style="color: var(--text-primary);">The Meta Ads Sales Funnel Architecture</h2>
        <p class="section-subtitle" style="color: var(--text-secondary);">How we move strangers to loyal customers systematically.</p>
      </div>
      <div class="content-text reveal" style="color: var(--text-secondary); font-size: 1.1rem; line-height: 1.8; max-width: 1000px; margin: 0 auto;">
        <p style="margin-bottom: 30px; text-align: center;">
          Unlike search engines, users on social media are not actively looking to buy your product. We must guide them through a carefully orchestrated psychological journey.
        </p>
        
        <div style="display: flex; flex-direction: column; gap: 20px;">
          <div style="background: rgba(31,83,151,0.05); border: 1px solid rgba(31,83,151,0.2); padding: 30px; border-radius: 8px;">
            <h4 style="color: var(--accent-blue); margin-bottom: 10px; font-size: 1.3rem;">Top of Funnel (TOFU) - Cold Audiences</h4>
            <p><strong>Goal: Awareness & Engagement.</strong> We target broad audiences in Surat using visually stunning, educational, or highly entertaining video content. The objective is simply to get them to stop scrolling, watch the video, and introduce them to your brand.</p>
          </div>
          <div style="text-align: center; color: var(--accent-blue);"><i class="fas fa-arrow-down fa-2x"></i></div>
          <div style="background: rgba(31,83,151,0.05); border: 1px solid rgba(31,83,151,0.2); padding: 30px; border-radius: 8px;">
            <h4 style="color: var(--accent-blue); margin-bottom: 10px; font-size: 1.3rem;">Middle of Funnel (MOFU) - Retargeting</h4>
            <p><strong>Goal: Consideration & Lead Gen.</strong> We create custom audiences of people who watched 50% of your TOFU video or engaged with your Instagram profile. We retarget them with ads that overcome objections—client testimonials, case studies, or detailed product carousels.</p>
          </div>
          <div style="text-align: center; color: var(--accent-blue);"><i class="fas fa-arrow-down fa-2x"></i></div>
          <div style="background: rgba(31,83,151,0.05); border: 1px solid rgba(31,83,151,0.2); padding: 30px; border-radius: 8px;">
            <h4 style="color: var(--accent-blue); margin-bottom: 10px; font-size: 1.3rem;">Bottom of Funnel (BOFU) - Sales Campaigns</h4>
            <p><strong>Goal: Direct Conversion.</strong> We target website visitors, cart abandoners, or highly nurtured leads with aggressive, direct-response ads. These feature strong calls to action, limited-time offers, or dynamic catalogue ads pushing them to finalize the transaction or CRM automation triggering the final sales call.</p>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- Section 8: Creative Strategy for Meta Ads -->
  <section class="section" style="background-color: var(--bg-secondary); border-top: 1px solid var(--glass-border); padding: 100px 0;">
    <div class="container">
      <div class="section-header reveal" style="text-align: center; margin-bottom: 50px;">
        <h2 class="section-title" style="color: var(--text-primary);">Creative Strategy: The New Targeting</h2>
        <p class="section-subtitle" style="color: var(--text-secondary);">With AI managing the bidding, your ad creative dictates your success.</p>
      </div>
      <div class="surat-grid-2 reveal">
        <div style="background: var(--bg-primary); padding: 40px; border-radius: 12px; border: 1px solid var(--glass-border);">
          <h3 style="color: var(--text-primary); margin-bottom: 20px;">Why Creatives Dominate</h3>
          <p style="color: var(--text-secondary); line-height: 1.8; margin-bottom: 20px;">
            In the past, you could win on Facebook by hacking the audience targeting settings. Today, Meta's machine learning is smarter than any media buyer. The algorithm determines who your ideal customer is based on <em>who stops to engage with your creative</em>. The creative is the targeting.
          </p>
          <ul style="color: var(--text-secondary); line-height: 1.8; padding-left: 20px;">
            <li><strong>UGC (User Generated Content):</strong> Authentic, selfie-style review videos that blend naturally into Reels. Critical for D2C brands.</li>
            <li><strong>Founder Stories:</strong> Builds immense local trust for service providers and real estate developers in Surat.</li>
            <li><strong>Carousel Ads:</strong> Perfect for showcasing multiple product lines or real estate floor plans sequentially.</li>
            <li><strong>Offer Ads:</strong> Bold, text-heavy static images used exclusively at the bottom of the funnel to drive immediate action.</li>
          </ul>
        </div>
        <div style="background: var(--bg-primary); padding: 40px; border-radius: 12px; border: 1px solid var(--glass-border);">
          <h3 style="color: var(--text-primary); margin-bottom: 20px;">The 3-Second Hook</h3>
          <p style="color: var(--text-secondary); line-height: 1.8; margin-bottom: 20px;">
            You have roughly 3 seconds to stop a user from scrolling past your ad. If the visual hook or the opening headline fails, the rest of the video does not matter.
          </p>
          <p style="color: var(--text-secondary); line-height: 1.8;">
            We rigorously test different hooks against the same core messaging. We experiment with text overlays, fast-paced edits, contrarian statements, and highly relatable local scenarios to find the exact hook that captivates your specific audience in Surat.
          </p>
        </div>
      </div>
    </div>
  </section>

  <!-- Section 9 & 10: Lead Generation & Ecommerce Opportunities -->
  <section class="section" style="padding: 100px 0;">
    <div class="container">
      <div class="surat-grid-2">
        <div class="reveal">
          <h2 style="color: var(--text-primary); margin-bottom: 25px;">High-Ticket Lead Generation in Surat</h2>
          <p style="color: var(--text-secondary); line-height: 1.8; margin-bottom: 20px; font-size: 1.1rem;">
            For B2B services, real estate, clinics, and interior designers, Meta Ads offer unparalleled lead generation capabilities. 
          </p>
          <p style="color: var(--text-secondary); line-height: 1.8; font-size: 1.1rem;">
            We bypass complex websites by utilizing native Facebook Lead Forms and direct WhatsApp funnels. This minimizes friction. For high-ticket items, we implement appointment booking funnels—driving traffic to a landing page where prospects can schedule a consultation call directly with your sales team, completely pre-qualified.
          </p>
        </div>
        <div class="reveal">
          <h2 style="color: var(--text-primary); margin-bottom: 25px;">Ecommerce & Scaling Sales</h2>
          <p style="color: var(--text-secondary); line-height: 1.8; margin-bottom: 20px; font-size: 1.1rem;">
            Surat is witnessing a massive surge in D2C (Direct-to-Consumer) fashion, textile, and lifestyle brands. Meta Ads are the engine for this growth.
          </p>
          <p style="color: var(--text-secondary); line-height: 1.8; font-size: 1.1rem;">
            We implement comprehensive ecommerce funnels using Dynamic Catalogue Ads that sync directly with your inventory. We run aggressive conversion campaigns optimizing purely for 'Purchases', and deploy sophisticated post-purchase remarketing strategies to increase Customer Lifetime Value (LTV) and encourage repeat purchases.
          </p>
        </div>
      </div>
      <div class="reveal" style="margin-top: 50px; text-align: center; display: flex; justify-content: center; width: 100%;">
        <a href="free-audit" class="btn btn-primary glow-btn" style="padding: 15px 35px; background: #DC2626; display: inline-block;">Speak With Our Growth Team <i class="fas fa-arrow-right"></i></a>
      </div>
    </div>
  </section>

  <!-- Section 11: Meta Pixel, Tracking & Automation -->
  <section class="section" style="background-color: var(--bg-secondary); border-top: 1px solid var(--glass-border); padding: 100px 0;">
    <div class="container">
      <div class="section-header reveal" style="text-align: center; margin-bottom: 50px;">
        <h2 class="section-title" style="color: var(--text-primary);">Data Infrastructure: Tracking & Automation</h2>
        <p class="section-subtitle" style="color: var(--text-secondary);">Without accurate tracking, you are flying blind.</p>
      </div>
      <div class="grid-list reveal surat-grid-3">
        <div style="background: var(--bg-primary); padding: 35px; border-radius: 12px; border: 1px solid var(--glass-border);">
          <div style="font-size: 2.2rem; color: var(--accent-blue); margin-bottom: 15px;"><i class="fas fa-code"></i></div>
          <h3 style="color: var(--text-primary); margin-bottom: 15px;">Pixel & Conversion API (CAPI)</h3>
          <p style="color: var(--text-secondary); font-size: 1rem; line-height: 1.6;">We implement server-side tracking (CAPI) alongside the standard Meta Pixel to bypass iOS ad-blockers and Safari cookie restrictions, ensuring the ad algorithm receives 100% accurate conversion data to optimize against.</p>
        </div>
        <div style="background: var(--bg-primary); padding: 35px; border-radius: 12px; border: 1px solid var(--glass-border);">
          <div style="font-size: 2.2rem; color: var(--accent-blue); margin-bottom: 15px;"><i class="fas fa-project-diagram"></i></div>
          <h3 style="color: var(--text-primary); margin-bottom: 15px;">CRM Integrations</h3>
          <p style="color: var(--text-secondary); font-size: 1rem; line-height: 1.6;">Every lead generated from Meta Ads is automatically routed instantly into your CRM or Google Sheets. No manual downloading of CSV files. Your sales team receives an instant notification to call the prospect while intent is highest.</p>
        </div>
        <div style="background: var(--bg-primary); padding: 35px; border-radius: 12px; border: 1px solid var(--glass-border);">
          <div style="font-size: 2.2rem; color: var(--accent-blue); margin-bottom: 15px;"><i class="fab fa-whatsapp"></i></div>
          <h3 style="color: var(--text-primary); margin-bottom: 15px;">Marketing Automation</h3>
          <p style="color: var(--text-secondary); font-size: 1rem; line-height: 1.6;">We set up automated WhatsApp and Email nurture sequences. If a prospect fills out a lead form, they immediately receive a customized WhatsApp message with a brochure or an introductory video, drastically increasing conversion rates.</p>
        </div>
      </div>
    </div>
  </section>

  <!-- Section 12: Recommended Meta Ads Budgets -->
  <section class="section" style="padding: 100px 0;">
    <div class="container">
      <div class="section-header reveal" style="text-align: center; margin-bottom: 50px;">
        <h2 class="section-title" style="color: var(--text-primary);">Recommended Meta Ads Budgets</h2>
        <p class="section-subtitle" style="color: var(--text-secondary);">Realistic financial planning for sustainable growth.</p>
      </div>
      <div class="grid-list reveal surat-grid-2">
        <div style="background: rgba(255,255,255,0.02); padding: 35px; border-radius: 12px; border: 1px solid var(--glass-border);">
          <h3 style="color: var(--text-primary); margin-bottom: 10px;">Small & Local Businesses</h3>
          <p style="color: var(--accent-blue); font-weight: 600; margin-bottom: 15px; font-size: 1.1rem;">Suggested Monthly Spend: ₹20,000 - ₹40,000</p>
          <p style="color: var(--text-secondary); line-height: 1.6;">Ideal for local clinics, cafes, or boutique salons in Surat seeking hyper-local awareness and direct WhatsApp inquiries within a small geographic radius.</p>
        </div>
        <div style="background: rgba(255,255,255,0.02); padding: 35px; border-radius: 12px; border: 1px solid var(--glass-border);">
          <h3 style="color: var(--text-primary); margin-bottom: 10px;">Medium & Service Businesses</h3>
          <p style="color: var(--accent-blue); font-weight: 600; margin-bottom: 15px; font-size: 1.1rem;">Suggested Monthly Spend: ₹50,000 - ₹1,50,000</p>
          <p style="color: var(--text-secondary); line-height: 1.6;">Perfect for interior designers, mid-tier real estate brokers, and educational institutes. Requires a proper mix of video creatives and structured lead generation funnels.</p>
        </div>
        <div style="background: rgba(255,255,255,0.02); padding: 35px; border-radius: 12px; border: 1px solid var(--glass-border);">
          <h3 style="color: var(--text-primary); margin-bottom: 10px;">Scaling Ecommerce & D2C Brands</h3>
          <p style="color: var(--accent-blue); font-weight: 600; margin-bottom: 15px; font-size: 1.1rem;">Suggested Monthly Spend: ₹2,00,000 - ₹5,00,000+</p>
          <p style="color: var(--text-secondary); line-height: 1.6;">Required for aggressive national scaling. Includes high-frequency creative testing, dynamic retargeting, and rigorous pixel optimization to maintain a profitable ROAS.</p>
        </div>
        <div style="background: rgba(255,255,255,0.02); padding: 35px; border-radius: 12px; border: 1px solid var(--glass-border);">
          <h3 style="color: var(--text-primary); margin-bottom: 10px;">High-Ticket & Enterprise</h3>
          <p style="color: var(--accent-blue); font-weight: 600; margin-bottom: 15px; font-size: 1.1rem;">Custom Scaling Budgets</p>
          <p style="color: var(--text-secondary); line-height: 1.6;">For luxury real estate developers and massive jewellery brands. Focuses on high-end video production, long-term brand building, and complex, multi-touchpoint attribution models.</p>
        </div>
      </div>
    </div>
  </section>

  <!-- Section 13: Why Businesses Choose Meta Ads -->
  <section class="section" style="background-color: var(--bg-secondary); border-top: 1px solid var(--glass-border); padding: 100px 0;">
    <div class="container">
      <div class="section-header reveal" style="text-align: center; margin-bottom: 50px;">
        <h2 class="section-title" style="color: var(--text-primary);">Why Modern Businesses Rely on Meta Ads</h2>
        <p class="section-subtitle" style="color: var(--text-secondary);">The cornerstone of modern customer acquisition strategies.</p>
      </div>
      <div class="content-text reveal" style="color: var(--text-secondary); font-size: 1.1rem; line-height: 1.8; max-width: 1000px; margin: 0 auto; text-align: center;">
        <p style="margin-bottom: 20px;">
          Surat's businesses can no longer rely solely on foot traffic or traditional media like billboards and print, which lack tracking and precise targeting. Meta Ads offer the lowest barrier to entry coupled with the highest potential for scalable growth. 
        </p>
        <p style="margin-bottom: 20px;">
          They allow you to validate product-market fit rapidly, build immense social proof through comments and shares, and surgically target your exact ideal customer profile. From building local brand dominance to scaling a national ecommerce empire, Meta Ads provide the visual canvas and algorithmic power to transform your business trajectory.
        </p>
      </div>
    </div>
  </section>

  <!-- Section 14: Nearby Cities We Serve -->
  <section class="section" style="padding: 80px 0;">
    <div class="container text-center reveal" style="text-align: center;">
      <h2 style="color: var(--text-primary); margin-bottom: 20px; text-align: center;">Nearby Cities We Serve</h2>
      <p style="color: var(--text-secondary); line-height: 1.8; max-width: 700px; margin: 0 auto; text-align: center;">
        Beyond Surat, we manage high-performance Meta Ads campaigns for ambitious businesses across the South Gujarat commercial corridor:
      </p>
      <div style="display: flex; justify-content: center; gap: 20px; margin-top: 40px; flex-wrap: wrap;">
        <div class="city-pill">Navsari</div>
        <div class="city-pill">Vapi</div>
        <div class="city-pill">Bharuch</div>
        <div class="city-pill">Valsad</div>
        <div class="city-pill">Ankleshwar</div>
        <div class="city-pill">Vadodara</div>
      </div>
    </div>
  </section>

  <!-- Section 15: Frequently Asked Questions -->
  <section class="section" style="background-color: var(--bg-secondary); border-top: 1px solid var(--glass-border); padding: 100px 0;">
    <div class="container">
      <div class="section-header reveal" style="text-align: center; margin-bottom: 50px;">
        <h2 class="section-title" style="color: var(--text-primary);">Frequently Asked Questions</h2>
        <p class="section-subtitle" style="color: var(--text-secondary);">Everything you need to know about scaling with Facebook & Instagram Ads.</p>
      </div>
      
      <div class="faq-container reveal" style="max-width: 800px; margin: 0 auto;" id="faq-list">
        <!-- FAQs will be generated dynamically based on the python dict below to match structure -->
"""

faq_html = ""
for i, faq in enumerate(meta_faqs, 1):
    faq_html += f'''
        <div class="faq-accordion">
          <button class="faq-question">{i}. {faq["q"]} <i class="fas fa-chevron-down"></i></button>
          <div class="faq-answer"><p>{faq["a"]}</p></div>
        </div>
'''

new_body += faq_html + """
      </div>
      
      <script>
        document.addEventListener('DOMContentLoaded', () => {
          document.querySelectorAll('.faq-question').forEach(button => {
            button.addEventListener('click', (e) => {
              e.preventDefault();
              const accordion = button.parentElement;
              const isActive = accordion.classList.contains('active');
              
              document.querySelectorAll('.faq-accordion').forEach(acc => acc.classList.remove('active'));
              
              if (!isActive) {
                accordion.classList.add('active');
              }
            });
          });
        });
      </script>
    </div>
  </section>
  
  <!-- Final Call to Action -->
  <section class="cta-section text-center reveal" style="padding: 100px 0; background: linear-gradient(135deg, rgba(31,83,151,0.1) 0%, rgba(31,83,151,0) 100%); border-top: 1px solid var(--glass-border);">
    <div class="container" style="max-width: 800px; margin: 0 auto; display: flex; flex-direction: column; align-items: center;">
      <h2 style="font-size: 2.5rem; margin-bottom: 20px; color: var(--text-primary);">Ready to Scale Your Business?</h2>
      <p style="font-size: 1.1rem; color: var(--text-secondary); margin-bottom: 40px; line-height: 1.6; text-align: center;">Stop wasting budget on ineffective boosting. Let us build a data-driven Meta Ads funnel that generates predictable revenue.</p>
      <a href="free-audit" class="btn btn-primary glow-btn" style="font-size: 1.1rem; padding: 18px 40px; background-color: #DC2626; color: #fff;">Request a Free Meta Ads Audit <i class="fas fa-arrow-right"></i></a>
    </div>
  </section>
"""

# Now replace the body content in the original file
# Find the start of the body content we want to replace and the end (before footer)
body_start = content.find('<!-- Hero Section -->')
if body_start == -1:
    body_start = content.find('<!-- Section 1: Hero Section -->')
if body_start == -1:
    body_start = content.find('<section class="hero')
    
footer_start = content.find('<footer class="footer"')

final_html = header + "\n" + new_body + "\n" + footer

with open(outpath, 'w', encoding='utf-8') as f:
    f.write(final_html)

print("Generated meta-ads-in-surat.html successfully.")
